#ifndef CONFIGURATION_H
#define CONFIGURATION_H

#define SERIAL_PORT Serial
#define SERIAL_PORT_SPEED 38400
#define SERIAL_RX_PIN 0
#define RTC_POWER_PIN 4
#define LED_SYNC LED_BUILTIN
#define DISPLAY_ADDR 0x78
#define MAIN_SCREEN_FONT u8g2_font_profont22_mn

#define DEBUG_SERIAL_PORT SERIAL_PORT

#endif
