set(ARDUINO_VER "10805" CACHE STRING "Arduino version define, 10805 == 1.8.5")
set(ARDUINO_MODEL "ARDUINO_AVR_PRO" CACHE STRING "Arduino board define")
set(ARDUINO_VARIANT "standard" CACHE STRING "Arduino board variant")


set(CMAKE_CXX_FLAGS "${ARDUINO_CXX_FLAGS_FULL} -DARDUINO=${ARDUINO_VER} -D${ARDUINO_MODEL}" CACHE INTERNAL "CMAKE_CXX_FLAGS")
set(CMAKE_CXX_FLAGS_RELEASE "" CACHE INTERNAL "CMAKE_CXX_FLAGS_RELEASE")
set(CMAKE_CXX_FLAGS_DEBUG "-DDEBUG" CACHE INTERNAL "CMAKE_CXX_FLAGS_DEBUG")
set(CMAKE_C_FLAGS "${ARDUINO_C_FLAGS_FULL} -DARDUINO=${ARDUINO_VER} -D${ARDUINO_MODEL}" CACHE INTERNAL "CMAKE_C_FLAGS")
set(CMAKE_C_FLAGS_RELEASE "" CACHE INTERNAL "CMAKE_C_FLAGS_RELEASE")
set(CMAKE_C_FLAGS_DEBUG "-DDEBUG" CACHE INTERNAL "CMAKE_C_FLAGS_DEBUG")
set(CMAKE_ASM_FLAGS "${ARDUINO_ASM_FLAGS_FULL} -DARDUINO=${ARDUINO_VER} -D${ARDUINO_MODEL}" CACHE INTERNAL "CMAKE_ASM_FLAGS")
set(CMAKE_EXE_LINKER_FLAGS "${EXE_LINKER_FLAGS_FULL}" CACHE INTERNAL "CMAKE_EXE_LINKER_FLAGS")
